library(lubridate)
fileName <- "household_power_consumption.txt"
top5rows <- read.table(fileName, header = TRUE, sep = ";", na.string = "?", nrows = 5)
classes <- sapply(top5rows, class)
raw_data <- read.table(fileName, header = TRUE, sep = ";", na.string = "?", colClasses = classes)
selected <- raw_data[raw_data$Date == "1/2/2007"| raw_data$Date == '2/2/2007',]
rm(raw_data)
selected$Date <- as.Date(strptime(selected$Date, "%d/%m/%Y"))
selected$Time <- hms(selected$Time)
selected <-  cbind(selected, DateTime = selected$Date + selected$Time)
png(file = "plot4.png")
par(mfrow = c(2,2),mar=c(4,4,2,1),oma = c(0,0,2,0))
with(selected, {plot(DateTime, Global_active_power,type="l",ylab = "Global Active Power")
                plot(DateTime, Voltage, type = "l",xlab = "datetime", ylab="Voltage")
                plot(DateTime, Sub_metering_1, type="l", xlab="",ylab="Energy submetering",col="black")
                lines(DateTime, Sub_metering_2,type="l",xlab="",ylab="Energy submetering",col="red")
                lines(DateTime, Sub_metering_3,type="l",xlab="",ylab="Energy submetering",col="blue")
                legend("topright",c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("Black", "red","blue"),lty = c(1,1))
                plot(DateTime, Global_reactive_power, type = "l",xlab = "datetime", ylab="Global_reactive_power")
})
dev.off()